name: Upload Go Binaries on Release

on:
  release:
    types:
      - created

permissions:
  contents: write

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Build binaries
      run: |
        mkdir -p dist
        GOOS=linux GOARCH=amd64 go build -o dist/memkill-linux-amd64 main.go

    - name: Install GitHub CLI
      run: sudo apt-get install -y gh

    - name: Upload Linux binary
      run: gh release upload ${{ github.event.release.tag_name }} dist/memkill-linux-amd64 --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
